---
  - name: Update apt
    become: yes
    become_user: root
    become_method: sudo
    apt:  update_cache=yes

  - name: Install system packages
    become: yes
    become_user: root
    become_method: sudo
    apt:  pkg={{ item }} state=latest
    with_items:
      - curl
      - wget
      - build-essential
      - python-software-properties

  - name: Add ppa repository
    become: yes
    become_user: root
    become_method: sudo
    apt_repository: repo=ppa:ondrej/{{ php_ppa }}

  - name: Update apt again
    become: yes
    become_user: root
    become_method: sudo
    apt:  update_cache=yes

  - name: Install extra packages
    become: yes
    become_user: root
    become_method: sudo
    apt:  pkg={{ item }} state=latest
    with_items: "{{ sys_packages }}"
