---
- hosts: all
  sudo:  true
  vars:
    doc_root: /var/www/web
    sys_packages:
      - mcrypt
      - unzip
      - vim
      - multitail
    php_packages:
      - { name: dev, package: php7.0-dev }
      - { name: xdebug, package: php7.0-xdebug }
      - { name: curl, package: php7.0-curl }
      - { name: mcrypt, package: php7.0-mcrypt }
      - { name: mysql, package: php7.0-mysql }
      - { name: redis, package: php7.0-redis }
      - { name: memcached, package: php7.0-memcached }
      - { name: sqlite, package: php7.0-sqlite3 }
      - { name: gd, package: php7.0-gd }
    php_ppa: php
    nodejs:
      version: _5.x
      packages: [casperjs, phantomjs, bower, gulp]
  roles:
    - init
    - nginx
    - php7-fpm
    - php7-cli
    - php7-common
    - composer
    - phpunit
    - mysql
    - git
    - curl
    - sqlite
    - wget
    - rabbitmq
    - redis
    - memcached
    - nodejs
