---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  vars:
    doc_root: /var/www/web
    sys_packages:
      - mcrypt
      - unzip
      - vim
      - multitail
    php_packages:
      - { name: dev, package: php7.1-dev }
      - { name: xdebug, package: php7.1-xdebug }
      - { name: curl, package: php7.1-curl }
      - { name: mcrypt, package: php7.1-mcrypt }
      - { name: mysql, package: php7.1-mysql }
      - { name: redis, package: php7.1-redis }
      - { name: memcached, package: php7.1-memcached }
      - { name: sqlite, package: php7.1-sqlite3 }
      - { name: gd, package: php7.1-gd }
    php_ppa: php
    nodejs:
      version: _8.x
      packages:
        - casperjs
      #  - phantomjs2
        - bower
        - gulp
  roles:
    - init
    - nginx
    - php7-fpm
    - php7-cli
    - php7-common
    - composer
    - phpunit
    - mysql
    - git
    - curl
    - sqlite
    - wget
    - rabbitmq
    - redis
    - memcached
    - nodejs
