---
- name: Install PHP packages
  become: yes
  become_user: root
  become_method: sudo
  apt:  package={{ item.package }} state=latest
  with_items: "{{ php_packages }}"

- name: Enable PHP packages
  become: yes
  become_user: root
  become_method: sudo
  command: /usr/sbin/phpenmod {{ item.name }} creates=/etc/php/7.1/cli/conf.d/20-{{ item.name }}.ini
  with_items: "{{ php_packages }}"
  notify: restart php7.1-fpm

#- name: Install PHP extensions
#  sudo: yes
#  shell: echo "\n" | /usr/bin/pecl install {{ item.package }} creates=/usr/lib/php/7.0/{{ item.name }}.so
#  with_items: php_extensions
#
#- name: Configure PHP extensions
#  sudo: yes
#  template: src=extension.tpl dest=/etc/php/7.0/mods-available/{{ item.name }}.ini
#  with_items: php_extensions
#
#- name: Enable PHP extensions
#  sudo: yes
#  command: /usr/sbin/phpenmod {{ item.name }} creates=/etc/php/7.0/cli/conf.d/20-{{ item.name }}.ini
#  with_items: php_extensions
#  notify: restart php7.1-fpm
